"""add template snapshot to assessment attempts

Revision ID: 0fe39298461d
Revises: 7fe20b73e9d2
Create Date: 2026-09-11 09:26:30.745945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fe39298461d'
down_revision: Union[str, Sequence[str], None] = '7fe20b73e9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_attempts', sa.Column('template_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_attempts', 'template_snapshot')
    # ### end Alembic commands ###
