"""add applications table

Revision ID: 6257655245e0
Revises: f9d26d7ef36a
Create Date: 2026-09-05 21:37:43.448507

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision: str = '6257655245e0'
down_revision: Union[str, Sequence[str], None] = 'f9d26d7ef36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_post_id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resume_object_key', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('submitted', 'under_review', 'accepted', 'rejected', 'withdrawn')", name='ck_applications_status'),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_applications_active_per_job_post', 'applications', ['job_post_id', 'applicant_id'], unique=True, postgresql_where=sa.text("status != 'withdrawn'"))
    # ### end Alembic commands ###

    # Seed the manage_applications permission and grant it to admin + hr,
    # matching the manage_jobs seed from the jobs-domain migration. Role ids
    # are looked up by name rather than hardcoded, since they're generated
    # fresh (uuid.uuid4()) whenever the RBAC migration actually runs.
    bind = op.get_bind()

    roles_table = table("roles", column("id", sa.UUID()), column("name", sa.String()))
    permissions_table = table(
        "permissions",
        column("id", sa.UUID()),
        column("key", sa.String()),
        column("description", sa.String()),
    )
    role_permissions_table = table(
        "role_permissions",
        column("role_id", sa.UUID()),
        column("permission_id", sa.UUID()),
    )

    admin_id = bind.execute(
        sa.select(roles_table.c.id).where(roles_table.c.name == "admin")
    ).scalar_one()
    hr_id = bind.execute(
        sa.select(roles_table.c.id).where(roles_table.c.name == "hr")
    ).scalar_one()

    manage_applications_id = uuid.uuid4()
    op.bulk_insert(
        permissions_table,
        [
            {
                "id": manage_applications_id,
                "key": "manage_applications",
                "description": "View and decide on job applications (any "
                "job post, any applicant)",
            }
        ],
    )
    op.bulk_insert(
        role_permissions_table,
        [
            {"role_id": admin_id, "permission_id": manage_applications_id},
            {"role_id": hr_id, "permission_id": manage_applications_id},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    permissions_table = table(
        "permissions", column("id", sa.UUID()), column("key", sa.String())
    )
    role_permissions_table = table(
        "role_permissions", column("permission_id", sa.UUID())
    )
    manage_applications_id = bind.execute(
        sa.select(permissions_table.c.id).where(
            permissions_table.c.key == "manage_applications"
        )
    ).scalar_one_or_none()
    if manage_applications_id is not None:
        bind.execute(
            role_permissions_table.delete().where(
                role_permissions_table.c.permission_id == manage_applications_id
            )
        )
        bind.execute(
            permissions_table.delete().where(
                permissions_table.c.id == manage_applications_id
            )
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_applications_active_per_job_post', table_name='applications', postgresql_where=sa.text("status != 'withdrawn'"))
    op.drop_table('applications')
    # ### end Alembic commands ###
