"""add resume_screening_consent_at to users

Revision ID: ce3afa1f8273
Revises: 76ce43cc59d8
Create Date: 2026-09-16 09:03:54.871597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3afa1f8273'
down_revision: Union[str, Sequence[str], None] = '76ce43cc59d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume_screening_consent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume_screening_consent_at')
    # ### end Alembic commands ###
