"""add assessments pipeline: templates, attempts, deadlines, status expansion

Revision ID: f4d2d1f8394c
Revises: 6257655245e0
Create Date: 2026-09-05 23:26:44.427901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4d2d1f8394c'
down_revision: Union[str, Sequence[str], None] = '6257655245e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-added: alembic's autogenerate does not detect CheckConstraint
    # content changes, only column/table/index/FK changes. The applications
    # status pipeline expanded from 5 values to 8
    # (applied/prescreening/interview/denied/success/failed/disqualified/
    # withdrawn) — see docs/plans/applications-status-pipeline.md. No
    # existing rows to backfill (confirmed empty applications table).
    op.drop_constraint('ck_applications_status', 'applications', type_='check')
    op.create_check_constraint(
        'ck_applications_status',
        'applications',
        "status IN ('applied', 'prescreening', 'interview', 'denied', "
        "'success', 'failed', 'disqualified', 'withdrawn')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('instructions', sa.String(length=4000), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('pre_assessment', 'culture_fit', 'technical')", name='ck_assessment_templates_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=2000), nullable=False),
    sa.Column('instructions', sa.String(length=1000), nullable=True),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.CheckConstraint("question_type IN ('text', 'long_text', 'single_choice', 'multiple_choice', 'boolean', 'number', 'rating', 'date', 'file_upload')", name='ck_assessment_questions_question_type'),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_post_assessment_templates',
    sa.Column('job_post_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_templates.id'], ),
    sa.PrimaryKeyConstraint('job_post_id', 'template_id'),
    sa.UniqueConstraint('job_post_id', 'type', name='ux_job_post_assessment_type')
    )
    op.create_table('assessment_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'completed', 'expired')", name='ck_assessment_attempts_status'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'template_id', name='ux_assessment_attempts_unique')
    )
    op.create_table('assessment_deadline_extensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('extended_by_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('previous_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extended_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extended_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('question_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_assessment_answers_live_per_question', 'assessment_answers', ['attempt_id', 'question_id'], unique=True, postgresql_where=sa.text('superseded_at IS NULL'))
    op.create_table('assessment_attempt_reopens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('reopened_by_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('reopened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reopened_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('applications', sa.Column('assessment_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_posts', sa.Column('assessment_window_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posts', 'assessment_window_days')
    op.drop_column('applications', 'assessment_deadline')
    op.drop_table('assessment_attempt_reopens')
    op.drop_index('ux_assessment_answers_live_per_question', table_name='assessment_answers', postgresql_where=sa.text('superseded_at IS NULL'))
    op.drop_table('assessment_answers')
    op.drop_table('assessment_deadline_extensions')
    op.drop_table('assessment_attempts')
    op.drop_table('job_post_assessment_templates')
    op.drop_table('assessment_questions')
    op.drop_table('assessment_templates')
    # ### end Alembic commands ###

    op.drop_constraint('ck_applications_status', 'applications', type_='check')
    op.create_check_constraint(
        'ck_applications_status',
        'applications',
        "status IN ('submitted', 'under_review', 'accepted', 'rejected', "
        "'withdrawn')",
    )
