"""add jobs domain: positions, tags, company addresses, job posts

Revision ID: f9d26d7ef36a
Revises: a86eaf9a012b
Create Date: 2026-09-05 18:51:13.032690

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision: str = 'f9d26d7ef36a'
down_revision: Union[str, Sequence[str], None] = 'a86eaf9a012b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('line1', sa.String(length=255), nullable=False),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_title'), 'positions', ['title'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=10000), nullable=False),
    sa.Column('requirements', sa.String(length=10000), nullable=False),
    sa.Column('qualifications', sa.String(length=10000), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('company_address_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("employment_type IN ('full_time', 'part_time', 'contract', 'internship', 'temporary')", name='ck_job_posts_employment_type'),
    sa.CheckConstraint("status IN ('draft', 'published', 'closed')", name='ck_job_posts_status'),
    sa.ForeignKeyConstraint(['company_address_id'], ['company_addresses.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_post_exclusions',
    sa.Column('job_post_id', sa.UUID(), nullable=False),
    sa.Column('excluded_job_post_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('job_post_id != excluded_job_post_id', name='ck_job_post_exclusion_not_self'),
    sa.ForeignKeyConstraint(['excluded_job_post_id'], ['job_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_post_id', 'excluded_job_post_id')
    )
    op.create_table('job_post_tags',
    sa.Column('job_post_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('job_post_id', 'tag_id')
    )
    # ### end Alembic commands ###

    # Seed the manage_jobs permission and grant it to admin + hr, matching the
    # shape of the manage_hr_accounts seed from the RBAC migration. Role ids
    # are looked up by name rather than hardcoded, since they're generated
    # fresh (uuid.uuid4()) whenever that earlier migration actually runs.
    bind = op.get_bind()

    roles_table = table("roles", column("id", sa.UUID()), column("name", sa.String()))
    permissions_table = table(
        "permissions",
        column("id", sa.UUID()),
        column("key", sa.String()),
        column("description", sa.String()),
    )
    role_permissions_table = table(
        "role_permissions",
        column("role_id", sa.UUID()),
        column("permission_id", sa.UUID()),
    )

    admin_id = bind.execute(
        sa.select(roles_table.c.id).where(roles_table.c.name == "admin")
    ).scalar_one()
    hr_id = bind.execute(
        sa.select(roles_table.c.id).where(roles_table.c.name == "hr")
    ).scalar_one()

    manage_jobs_id = uuid.uuid4()
    op.bulk_insert(
        permissions_table,
        [
            {
                "id": manage_jobs_id,
                "key": "manage_jobs",
                "description": "Create/update/delete job posts, positions, "
                "tags, and company addresses",
            }
        ],
    )
    op.bulk_insert(
        role_permissions_table,
        [
            {"role_id": admin_id, "permission_id": manage_jobs_id},
            {"role_id": hr_id, "permission_id": manage_jobs_id},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    permissions_table = table(
        "permissions", column("id", sa.UUID()), column("key", sa.String())
    )
    role_permissions_table = table(
        "role_permissions", column("permission_id", sa.UUID())
    )
    manage_jobs_id = bind.execute(
        sa.select(permissions_table.c.id).where(
            permissions_table.c.key == "manage_jobs"
        )
    ).scalar_one_or_none()
    if manage_jobs_id is not None:
        bind.execute(
            role_permissions_table.delete().where(
                role_permissions_table.c.permission_id == manage_jobs_id
            )
        )
        bind.execute(
            permissions_table.delete().where(permissions_table.c.id == manage_jobs_id)
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_post_tags')
    op.drop_table('job_post_exclusions')
    op.drop_table('job_posts')
    op.drop_table('tags')
    op.drop_index(op.f('ix_positions_title'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('company_addresses')
    # ### end Alembic commands ###
